// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3ANfxV3xdsPREig0lHeeN2vcn4yltTE',
    appId: '1:908171481549:web:19149264a20463bd5cf484',
    messagingSenderId: '908171481549',
    projectId: 'task-manager-973bf',
    authDomain: 'task-manager-973bf.firebaseapp.com',
    storageBucket: 'task-manager-973bf.firebasestorage.app',
    measurementId: 'G-R0S5BCVD78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJIisOhS5artVSbZzsj2beOXiZHV7Qqw',
    appId: '1:908171481549:android:08fa32be06cf9f265cf484',
    messagingSenderId: '908171481549',
    projectId: 'task-manager-973bf',
    storageBucket: 'task-manager-973bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnVeWvGW6b4Anmf9meFOAgQgu5zpVKw8o',
    appId: '1:908171481549:ios:1d3cbd7854dc69965cf484',
    messagingSenderId: '908171481549',
    projectId: 'task-manager-973bf',
    storageBucket: 'task-manager-973bf.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnVeWvGW6b4Anmf9meFOAgQgu5zpVKw8o',
    appId: '1:908171481549:ios:1d3cbd7854dc69965cf484',
    messagingSenderId: '908171481549',
    projectId: 'task-manager-973bf',
    storageBucket: 'task-manager-973bf.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN3ANfxV3xdsPREig0lHeeN2vcn4yltTE',
    appId: '1:908171481549:web:8aba1539caa297565cf484',
    messagingSenderId: '908171481549',
    projectId: 'task-manager-973bf',
    authDomain: 'task-manager-973bf.firebaseapp.com',
    storageBucket: 'task-manager-973bf.firebasestorage.app',
    measurementId: 'G-ZNEQ5B1250',
  );
}
